language: go

go:
  - 1.x

install: true

script:
  - set -e
  - fmt=$(gofmt -l .)
  - test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
  - go run golang.org/x/lint/golint -set_exit_status $(go list ./...)
  - go generate ./...
  - go test -race -vet=all -test.count=10 ./...

