version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ratings
      MYSQL_USER: ratings
      MYSQL_PASSWORD: ratings
  product-service:
    build: ./wiremock
    restart: always
    ports:
      - "8080:8080"
