version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ratings
      MYSQL_USER: ratings
      MYSQL_PASSWORD: ratings
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p", "root"]
      timeout: 20s
      retries: 10
  product-service:
    image: tessig/simple-productservice-mock:latest
    restart: always
    ports:
      - "8080:8080"
  migrate:
    build: ../.
    restart: on-failure
    command: --flamingo-config-log migrate up
    environment: &dbenv
      DBHOST: db
      DBPORT: 3306
      DBUSER: ratings
      DBPASSWORD: ratings
      DBNAME: ratings
    depends_on:
      - db
    links:
      - db
  seed:
    build: ../.
    restart: on-failure
    command: --flamingo-config-log seed
    environment: *dbenv
    depends_on:
      - db
      - migrate
    links:
      - db
  app:
    build: ../.
    restart: always
    ports:
      - "3322:3322"
      - "13210:13210"
    environment:
      <<: *dbenv
      PRODUCTSERVICEURL: http://product-service:8080
    links:
      - db
      - product-service
    depends_on:
      - db
      - product-service
      - migrate
      - seed
